import json
def mc(q, ok, w1, w2, why): return {"t":"mc","q":q,"o":[ok,w1,w2],"a":0,"why":why}
def fill(q, ans, why): return {"t":"fill","q":q,"a":ans if isinstance(ans,list) else [ans],"why":why}
def M(kind,title,source,url,minutes,focus): return {"kind":kind,"title":title,"source":source,"url":url,"minutes":minutes,"focus":focus}
def yt(vid,title,src,mins,focus): return M("video",title,"YouTube · "+src,"https://www.youtube.com/watch?v="+vid,mins,focus)
def N(h,t): return {"heading":h,"text":t}

MOD="https://www.goethe.de/pro/relaunch/prf/materialien/B1/b1_modellsatz_erwachsene.pdf"
UEB="https://www.goethe.de/pro/relaunch/prf/materialien/B1/B1_Uebungssatz_Erwachsene.pdf"
ONL="https://www.goethe.de/ins/de/de/spr/prf/gzb1/ueb.html"
def modell(mins,focus): return M("pdf","Goethe-Zertifikat B1 – Modellsatz (adults)","Goethe-Institut",MOD,mins,focus)
def uebung(mins,focus): return M("pdf","Goethe-Zertifikat B1 – Übungssatz (adults)","Goethe-Institut",UEB,mins,focus)
def online(mins,focus): return M("exercise","Goethe-Zertifikat B1 – practice tests with audio","Goethe-Institut",ONL,mins,focus)

# ---------- B1 level test ----------
test = {"b1": {
 "title":"B1 Level Test",
 "goal":"You have worked through 76 B1 lessons. Today you prove B1 before you start the 25 exam-prep days.",
 "notes":[
  N("How today works","1. Skim the review sheet (10 minutes).\n2. Take the official **Final Test B1** on Deutsche Welle (material 1) and note the result.\n3. Take today’s 25-question exam. You need **70%** to complete the day. If you miss it, read the explanations and retake."),
  N("Sentence structure and connectors","**Subordinate clauses** (verb at the end): weil, dass, wenn, als, ob, obwohl, damit, während, bevor, nachdem, seit(dem).\n**Main-clause adverbs** (verb in 2nd place): deshalb, deswegen, trotzdem, dagegen, jedoch, allerdings.\n**Double conjunctions:** entweder … oder, weder … noch, sowohl … als auch, nicht nur … sondern auch.\n**Purpose:** um … zu (same subject) / damit (different subjects).\n**Infinitive with zu:** Ich habe keine Lust, heute **zu** arbeiten. Separable: aufzustehen."),
  N("Tenses, passive and Konjunktiv","**Präteritum** (written/narrative): ging, kam, war, hatte. **Perfekt** (spoken). **Plusquamperfekt:** hatte/war + Partizip II (nachdem er gegessen hatte).\n**Passiv:** werden + Partizip II (wird gewählt, wurde gebaut, ist gebaut worden).\n**Konjunktiv II:** wäre, hätte, würde, könnte – wishes, advice, polite requests.\n**Futur I:** werden + Infinitiv (es wird wärmer werden)."),
  N("Cases, relative clauses, nouns","**Genitiv:** des Mannes, der Frau; wegen, trotz, während + Genitiv.\n**Relative clauses:** der Mann, **den** ich kenne · **dessen** Tochter · die Stadt, **wo** ich wohne.\n**n-Deklination:** der Student → den/dem/des Studenten.\n**Nouns:** -heit/-keit (die), -chen (das), -ung (die). **wo-compounds:** worauf, womit, wofür, worüber."),
 ],
 "materials":[
  M("exercise","Final Test B1 – Nicos Weg","Deutsche Welle","https://learngerman.dw.com/de/abschlusstest-b1/l-44070818",25,"Take the official course test and write down the score. Any unit where you hesitate is your review list."),
  M("pdf","Grammar overview B1 (Nicos Weg)","Deutsche Welle","https://static.dw.com/downloads/59838242/grammatikuebersicht-nicos-weg-b1.pdf",10,"Read all B1 grammar tables and mark the ones you cannot recite from memory."),
 ],
 "quiz":[
  fill("Ich weiß nicht, ___ er heute kommt. (whether)",["ob"],"Indirekte Ja/Nein-Frage → ob."),
  mc("Which sentence is correct?","Ich bleibe zu Hause, weil ich krank bin.","Ich bleibe zu Hause, weil ich bin krank.","Ich bleibe zu Hause, weil bin ich krank.","Nebensatz: Verb am Ende."),
  fill("Es regnet. ___ gehe ich spazieren. (nevertheless)",["Trotzdem"],"trotzdem + Verb an Position 2."),
  mc("Complete: Er ist nicht müde, ___ hungrig.","sondern","aber","denn","nicht … sondern."),
  fill("Ich mag weder Fisch ___ Fleisch.",["noch"],"weder … noch."),
  fill("Ich lerne Deutsch, ___ in Deutschland zu arbeiten.",["um"],"um … zu."),
  mc("“Ich helfe dir, ___ du früher fertig bist.”","damit","um","weil","Different subjects → damit."),
  fill("Gestern ___ ich lange im Büro. (sein, Präteritum)",["war"],"ich war."),
  fill("Nachdem er gegessen ___, ging er spazieren. (haben, Plusquamperfekt)",["hatte"],"hatte gegessen."),
  fill("Der Landtag ___ im nächsten Monat gewählt. (werden, Passiv)",["wird"],"wird gewählt."),
  fill("Der Kandidat ist gewählt ___. (Perfekt Passiv)",["worden"],"Perfekt Passiv: worden."),
  fill("Wenn ich mehr Zeit ___, würde ich reisen. (haben, Konjunktiv II)",["hätte","haette"],"ich hätte."),
  mc("Which sentence gives advice?","An deiner Stelle würde ich zum Arzt gehen.","Ich gehe zum Arzt.","Er war beim Arzt.","Konjunktiv II."),
  fill("Es ___ in Zukunft wärmer werden. (werden, Futur I)",["wird"],"es wird."),
  fill("___ des schlechten Wetters bleiben wir zu Hause. (because of)",["Wegen"],"wegen + Genitiv."),
  fill("Das ist der Mann, ___ Tochter Ärztin ist.",["dessen"],"dessen + Nomen ohne Artikel."),
  fill("Die Stadt, ___ ich geboren bin, ist klein.",["wo","in der"],"Relativadverb wo."),
  fill("Ich kenne den Student___. (n-Deklination, Akkusativ)",["en","Studenten"],"den Studenten."),
  mc("möglich → noun:","die Möglichkeit","das Möglich","der Möglichheit","-lich → -keit."),
  mc("Gender of a noun ending in -chen:","das","der","die","Diminutiv: immer neutrum."),
  fill("___ interessierst du dich? (for what)",["Wofür","Wofuer"],"wo(r) + für."),
  fill("Ich lerne seit einem Jahr Deutsch, ___ ich in Deutschland wohne. (since)",["seit","seitdem"],"seit(dem) + Nebensatz."),
  fill("Er lässt sich die Haare ___. (schneiden)",["schneiden"],"lassen + Infinitiv."),
  mc("Which comparison is correct?","Er ist so alt wie ich.","Er ist so älter wie ich.","Er ist älter wie ich.","so … wie; älter als."),
  mc("Which sentence contains the correct Genitiv?","Das Auto des Nachbarn steht hier.","Das Auto der Nachbarn steht hier (singular).","Das Auto dem Nachbarn steht hier.","Maskulin Genitiv: des …(e)s / n-Nomen: des Nachbarn."),
 ]}}
json.dump(test, open("content/src/tests-b1.json","w"), ensure_ascii=False, indent=0)

# ---------- Exam prep ----------
D = []  # one dict per day, days 194..218
def day(title, goal, notes, materials, quiz): D.append({"title":title,"goal":goal,"notes":notes,"materials":materials,"quiz":quiz})

day("Exam overview: four modules, 60% to pass",
 "Learn how the Goethe-Zertifikat B1 is built, how it is scored, and how you will use the next 25 days.",
 [N("The exam in one table","**Lesen** 65 min, 5 parts, 30 items. **Hören** 40 min, 4 parts, 30 items. **Schreiben** 60 min, 3 tasks (two e-mails and a forum/discussion post). **Sprechen** 15 min for two candidates (3 parts, 15 min preparation).\nEach module is worth **100 points**; you pass a module with **60 points (60%)**. You can take modules separately."),
  N("What B1 means","You can understand the main points of clear standard language on familiar topics (work, school, leisure), deal with most situations while travelling, produce simple connected text, describe experiences, dreams and goals, and give short reasons and explanations."),
  N("Your 25-day plan","Days 1–5 Lesen · 6–10 Hören · 11–15 Schreiben · 16–19 Sprechen · 20–22 Grammar and vocabulary review · 23–24 full mocks · 25 final mock exam. **Important:** this course follows the **Goethe-Zertifikat B1**. If you sit telc B1 or DTZ, the skills are the same but formats differ slightly – check your provider’s model test.")],
 [yt("y-5mkHkKGkM","Goethe-Zertifikat B1: Überblick und Module erklärt","Dr Popkins German",7,"Compare the four modules with the table above and note the timings."),
  modell(20,"Read the Vorwort and the overview table (pages 5–7) and note any difference to what you expected.")],
 [mc("How many points do you need to pass a module?","60 of 100","70 of 100","50 of 100","Bestehensgrenze 60%."),
  mc("How long is the Lesen module?","65 minutes","40 minutes","60 minutes","Lesen 65, Hören 40, Schreiben 60."),
  mc("How long is the Hören module?","40 minutes","65 minutes","15 minutes","Hören: 40 Minuten."),
  mc("How many tasks does Schreiben have?","3","5","4","2 E-Mails + 1 Diskussionsbeitrag."),
  mc("How many parts does Sprechen have?","3","2","5","Planen, Präsentieren, Reagieren."),
  mc("Can you take the modules separately?","Yes, modules can be taken individually","No, only all together","Only Lesen and Hören","Modular möglich."),
  mc("How many items does Lesen have?","30","20","50","6+6+7+7+4 = 30."),
  mc("How much preparation time do you get for Sprechen?","15 minutes","5 minutes","30 minutes","Vorbereitungszeit 15 Minuten."),
  mc("The B1 level is called …","selbstständige Sprachverwendung (independent user)","elementare Sprachverwendung","kompetente Sprachverwendung","Stufe B."),
  mc("Which skill is NOT tested?","Grammar as a separate module","Reading","Speaking","Grammatik wird in den vier Modulen mitgeprüft."),
 ])

# Lesen
day("Lesen Teil 1: Richtig oder Falsch",
 "Read a personal text (blog, e-mail) and decide for six statements whether they are richtig or falsch.",
 [N("Task","**10 minutes**, 6 items. You read one longer text (often a blog entry or letter) and decide whether each statement is **richtig** or **falsch**. The statements follow the order of the text."),
  N("Strategy","1. Skim the title and first sentences.\n2. Read statement 1 and find the passage – then move on in order.\n3. Watch for **synonyms**: the statement rarely uses the same words as the text.\n4. **Negation and quantities** (nie, immer, alle, nur, mehr als) are typical traps."),
  N("Useful words","**der Alltag** everyday life · **sich entscheiden für** decide on · **das Vorhaben** plan · **erleben** experience · **behaupten** claim · **im Gegenteil** on the contrary")],
 [yt("Lju3xdEzRhM","So lösen Sie Abschnitt 1 des Lesens superschnell! | B1 Deutsch-Vorbereitung","StudySmart",13,"Note the strategy; pause before each solution and decide yourself."),
  modell(15,"Do Lesen Teil 1 (10 minutes, timed) from the Modellsatz and check the key at the end.")],
 [mc("How much time do you have for Lesen Teil 1?","10 minutes","20 minutes","5 minutes","Teil 1: Arbeitszeit 10 Minuten."),
  mc("How many items are in Lesen Teil 1?","6","10","4","6 R/F items."),
  mc("What do the statements often use instead of the words in the text?","synonyms and paraphrases","exactly the same words","only numbers","Deshalb: Bedeutung vergleichen."),
  mc("The statements usually follow …","the order of the text","a random order","the last paragraph first","Reihenfolge im Text."),
  mc("“Er geht nie ins Kino.” In the text: “Er geht selten ins Kino.” The statement is …","falsch","richtig","not decidable","nie ≠ selten."),
  mc("“der Alltag” means:","everyday life","all day","allotment","Alltagsleben."),
  mc("“behaupten” means:","to claim","to keep","to attend","Er behauptet, dass …"),
  mc("“im Gegenteil” means:","on the contrary","in parts","in the middle","Gegensatz."),
  mc("If you do not find the answer, you should …","guess – there is no penalty for wrong answers","leave it empty","leave the exam","Immer eine Antwort geben."),
  mc("Which word is a typical trap?","nur","und","auch","nur/immer/nie ändern die Aussage."),
 ])

day("Lesen Teil 2: Pressetext, Mehrfachauswahl",
 "Understand a newspaper-style text and choose the right answer a, b or c.",
 [N("Task","**20 minutes**, 6 items (two short texts, three questions each). Choose a, b or c. Texts are from newspapers or magazines on topics like energy, work or society."),
  N("Strategy","1. Read the questions first, then the text.\n2. Mark the key words in each question.\n3. The wrong answers often contain words from the text but say something different.\n4. Answers follow the order of the text."),
  N("Useful words","**der Bericht** report · **die Entwicklung** development · **nach Angaben von** according to · **erneuerbare Energien** renewable energy · **vor allem** above all")],
 [yt("dPs_5QOR0WI","Solve Lesen Teil 2 in 10 Minutes | German B1 Prep","StudySmart",21,"Watch the method, then solve a Teil 2 yourself in 20 minutes."),
  modell(25,"Do Lesen Teil 2 (20 minutes, timed) from the Modellsatz and correct it.")],
 [mc("How many items are in Lesen Teil 2?","6","10","7","6 Mehrfachauswahl-Items."),
  mc("How much time does Lesen Teil 2 take?","20 minutes","10 minutes","15 minutes","20 Minuten."),
  mc("What is a good first step?","Read the questions before the text","Translate every word","Read only the last line","Fragen zuerst lesen."),
  mc("Wrong answers often …","use words from the text with a different meaning","are obviously silly","are always the longest","Ablenker."),
  mc("“die Entwicklung” means:","development","envelope","entrance","technische Entwicklung."),
  mc("“nach Angaben von” means:","according to","after the details of","without information","nach Angaben der Polizei."),
  mc("“vor allem” means:","above all","in front of everyone","before everything","vor allem Jugendliche."),
  mc("In the Modellsatz, the text of Teil 2 is about …","a village that uses renewable energy","football","a bank crisis","Feldheim in Brandenburg."),
  mc("Which type of answer is typical?","a, b or c","richtig/falsch","Ja/Nein","Mehrfachauswahl."),
  mc("Should you read every word?","No – focus on the parts that answer the questions","Yes, every word","Only headings","Selektives Lesen."),
 ])

day("Lesen Teil 3: Anzeigen zuordnen",
 "Match seven situations with the right advertisement (A–J); one situation has no matching ad.",
 [N("Task","**10 minutes**, 7 situations and 10 ads (A–J). Each ad can be used **once**; for **one situation there is no ad – write 0**. Ads come from newspapers, websites, notice boards."),
  N("Strategy","1. Read each situation and underline what the person **needs**.\n2. Skim all ads and label each with 2–3 keywords.\n3. Match the sure ones first.\n4. Check **all details** (time, price, age, place) – ads are designed with small differences."),
  N("Useful words","**das Angebot** offer · **die Anmeldung** registration · **die Öffnungszeiten** opening hours · **kostenlos** free · **geeignet für** suitable for · **ab sofort** from now on")],
 [yt("zN3jTw87Vrs","Lesen Teil 3 leicht lösen | Deutsch B1 Vorbereitung","StudySmart",18,"Note how the presenter eliminates ads and handles the 0 situation."),
  modell(15,"Do Lesen Teil 3 (10 minutes, timed) from the Modellsatz.")],
 [mc("How many ads are there in Teil 3?","10 (A–J)","7","5","7 Situationen, 10 Anzeigen."),
  mc("What do you write if no ad fits?","0","X","–","Für eine Situation gibt es keine Anzeige: 0."),
  mc("Can you use an ad twice?","No, only once","Yes, always","Only two ads","Jede Anzeige nur einmal."),
  mc("What is a good first step?","Underline what each person needs","Read all ads word by word first","Translate the ads","Bedürfnisse markieren."),
  mc("“kostenlos” means:","free of charge","expensive","cost-effective","gratis."),
  mc("“die Anmeldung” means:","registration","announcement","login","sich anmelden."),
  mc("“geeignet für” means:","suitable for","equal to","suited to nothing","für Anfänger geeignet."),
  mc("“ab sofort” means:","from now on","after a while","as soon as possible only","ab sofort geöffnet."),
  mc("Two ads seem right. What do you check?","Small details such as time, price, age","Which ad is longer","Which ad has an image","Details entscheiden."),
  mc("How many minutes is Lesen Teil 3?","10","20","15","10 Minuten."),
 ])

day("Lesen Teil 4: Meinungen – Ja oder Nein",
 "Read seven short opinions and decide for each person: Ja (for) or Nein (against).",
 [N("Task","**15 minutes**, 7 items. Several readers comment on a question (e.g. “Sollen gewalttätige Videospiele verboten werden?”). For each person decide **Ja** or **Nein** regarding the question."),
  N("Strategy","1. Formulate the question in your own words: *Ist die Person dafür?*\n2. Look for **contrast markers**: aber, allerdings, zwar … aber – the real opinion often comes after them.\n3. Beware of irony and of people who describe a problem but support the rule anyway."),
  N("Opinion words","**dafür / dagegen sein** to be for / against · **befürworten** support · **ablehnen** reject · **meiner Meinung nach** in my opinion · **zustimmen** agree · **verbieten** ban")],
 [yt("H4iwo1rZ2vk","Lesen Sie Teil 4: Geheimnisse enthüllt | Deutsch B1 Vorbereitung","StudySmart",13,"Note how to find the real opinion behind ‘zwar … aber’."),
  modell(20,"Do Lesen Teil 4 (15 minutes, timed) from the Modellsatz.")],
 [mc("How many items are in Lesen Teil 4?","7","6","4","7 Ja/Nein-Items."),
  mc("What are you asked to decide?","whether the person is for or against","whether the statement is true","which ad fits","Ist die Person dafür?"),
  mc("“Zwar finde ich es interessant, aber …” The real opinion is …","after ‘aber’","before ‘zwar’","not clear","aber leitet das Hauptargument ein."),
  mc("“dafür sein” means:","to be in favour","to be there","to be for sale","Ich bin dafür."),
  mc("“ablehnen” means:","to reject","to lean on","to relieve","Er lehnt den Vorschlag ab."),
  mc("“befürworten” means:","to support","to fear","to warn","Ich befürworte das Verbot."),
  mc("“verbieten” means:","to ban","to forbid to offer","to connect","Rauchen ist verboten."),
  mc("A writer says: “Ich verstehe die Sorgen, aber ein Verbot hilft nicht.” He is …","against a ban","for a ban","neutral","Nein."),
  mc("Which word shows contrast?","allerdings","deshalb","außerdem","allerdings = however."),
  mc("How much time does Lesen Teil 4 have?","15 minutes","10 minutes","20 minutes","15 Minuten."),
 ])

day("Lesen Teil 5 and full Lesen practice",
 "Understand written instructions (rules, house regulations) and then test yourself with a full Lesen module in 65 minutes.",
 [N("Teil 5","**10 minutes**, 4 items. A text with rules (Hausordnung, Nutzungsbedingungen, Teilnahmebedingungen). Choose a, b or c. Focus: **what is allowed, what is required, what is forbidden**."),
  N("Rule language","**man darf nicht / man muss / es ist verboten / es ist erlaubt zu** · **bitte beachten Sie** · **auf eigene Verantwortung** · **haften für** be liable for · **rechtzeitig** on time"),
  N("Time plan for the whole module","65 minutes = Teil 1: 10 · Teil 2: 20 · Teil 3: 10 · Teil 4: 15 · Teil 5: 10. Do **not** spend more than the plan, and write all answers on the answer sheet before time is up.")],
 [yt("itFw0oeLFXM","Deutsch B1 Lesen Teil 5 gelöst | Geheimnisse & Hacks","StudySmart",18,"Note how rules are paraphrased in the answers."),
  modell(65,"Full Lesen module (all 5 parts) in 65 minutes. Score it with the key: 60% = 18 of 30.")],
 [mc("How many items are in Lesen Teil 5?","4","6","7","Teil 5: 4 Items."),
  mc("What text type is Teil 5?","instructions or rules","a novel","a poem","Hausordnung etc."),
  mc("“es ist verboten” means:","it is forbidden","it is allowed","it is required","Verbot."),
  mc("“haften für” means:","to be liable for","to stick to","to arrest","Wir haften nicht für Schäden."),
  mc("“rechtzeitig” means:","on time, in good time","rightly","on the right side","rechtzeitig kommen."),
  mc("“bitte beachten Sie” means:","please note","please avoid","please pay","Hinweis."),
  mc("How many points is 60% of 30 items?","18","20","15","0,6 × 30 = 18."),
  mc("What do you do at the end of the module?","Copy answers to the answer sheet","Correct spelling","Read again all texts","Antworten übertragen."),
  mc("Time plan: how many minutes total?","65","60","70","10+20+10+15+10."),
  mc("A rule says: “Fahrräder dürfen nur im Hof abgestellt werden.” Bikes may be parked …","only in the yard","everywhere","in the hallway","nur im Hof."),
 ])

# Hören
day("Hören Teil 1: short texts, twice",
 "Understand five short announcements and messages; each is heard twice and has two tasks.",
 [N("Task","**10 items** (5 texts × 2). You hear each text **twice**. Tasks: **Richtig/Falsch** and **a/b/c**. Texts: voicemail, announcements at a station, radio short news, instructions."),
  N("Strategy","1. In the reading pause, mark the key words in both tasks.\n2. First listening: answer the first task. Second listening: check and answer the second.\n3. Numbers, times, places, and days are typical traps (“nicht am Montag, sondern am Dienstag”)."),
  N("Useful words","**die Durchsage** announcement · **die Ansage** message · **verschieben** postpone · **ausfallen** be cancelled · **Verspätung haben** be late · **abholen** pick up")],
 [yt("L16sNOrm9Io","Hören B1 | Telc DTZ | Tipps + Beispiele","Benjamin - Der Deutschlehrer",11,"Note the tips for the short texts."),
  online(20,"Do Hören Teil 1 of the Modellsatz with the audio, listen twice, then check.")],
 [mc("How many times do you hear each text in Teil 1?","twice","once","three times","Teil 1: zweimal."),
  mc("How many items are in Hören Teil 1?","10","5","7","5 Texte × 2 Aufgaben."),
  mc("“die Durchsage” means:","announcement","broadcast tower","passage","Durchsage am Bahnhof."),
  mc("“ausfallen” (Zug/Kurs) means:","to be cancelled","to fall out","to stand out","Der Kurs fällt aus."),
  mc("“verschieben” means:","to postpone","to shift a gear","to sell","Der Termin wird verschoben."),
  mc("“abholen” means:","to pick up","to fetch water","to hold off","Ich hole dich ab."),
  mc("In the pause before the text you should …","mark key words in the tasks","close your eyes","write your name","Aufgaben lesen!"),
  mc("A message: “Nicht am Montag, sondern am Dienstag.” The date is …","Tuesday","Monday","Wednesday","sondern korrigiert."),
  mc("Why is the second listening useful?","to check your answers","to translate","to memorise","Kontrolle."),
  mc("“Verspätung haben” means:","to be late","to have a special hat","to be early","Der Zug hat Verspätung."),
 ])

day("Hören Teil 2: a longer text, heard once",
 "Follow a longer text (tour, lecture, museum guide) and answer five multiple-choice tasks.",
 [N("Task","**5 items**, a/b/c. You hear **one** text **once**. In the Modellsatz it is a guided tour of a museum. You have **60 seconds** to read the tasks first."),
  N("Strategy","1. Use the 60 seconds to mark key words in all 5 questions.\n2. Tasks follow the **order of the text**.\n3. If you miss one, **move on** – do not lose the next one.\n4. Answers are often paraphrased."),
  N("Useful words","**die Führung** guided tour · **die Ausstellung** exhibition · **der Eintritt** admission · **geöffnet / geschlossen** open / closed · **Ermäßigung** discount")],
 [yt("6Bfucxf4LkM","Part 2 B1 Listening SOLVED!! | Tricks, Hacks & Audio","StudySmart",16,"Note the trick for keeping up with the order of the questions."),
  online(15,"Do Hören Teil 2 of the Modellsatz once, then check.")],
 [mc("How many times do you hear the text in Teil 2?","once","twice","three times","Nur einmal."),
  mc("How many items are in Teil 2?","5","7","8","5 Aufgaben."),
  mc("How long is the reading time before the text?","60 seconds","10 seconds","5 minutes","60 Sekunden."),
  mc("What if you miss one answer?","Move on to the next question","Stop listening","Ask the examiner","Weiter."),
  mc("“die Führung” means:","guided tour","leadership","management","Führung durch das Museum."),
  mc("“der Eintritt” means:","admission","entering","step in","Eintritt frei."),
  mc("“die Ermäßigung” means:","discount","moderation","reduction of pain","Studenten erhalten Ermäßigung."),
  mc("“geschlossen” means:","closed","included","concluded only","Das Museum ist geschlossen."),
  mc("Questions in Teil 2 follow …","the order of the text","random order","reverse order","Reihenfolge."),
  mc("In the Modellsatz Teil 2 is about …","a tour of a city museum","the weather","a job interview","Münchner Stadtmuseum."),
 ])

day("Hören Teil 3: a conversation, richtig/falsch",
 "Understand a conversation between two native speakers and mark seven statements as richtig or falsch.",
 [N("Task","**7 items**, R/F. You hear **one** conversation **once** (e.g. two people at a bus stop talking about a festival). Reading time: **60 seconds**."),
  N("Strategy","1. Mark subjects and key words in each statement.\n2. Watch for **who** says what and for **changes of mind** (“Ich wollte …, aber …”).\n3. Statements follow the conversation order."),
  N("Conversation phrases","**Weißt du was?** · **Das kann ich mir nicht vorstellen.** · **Da hast du recht.** · **Ich bin mir nicht sicher.** · **Übrigens …** · **Na ja …** · **Genau!**")],
 [yt("l38A0sXMgA0","German Exam Prep: How to Solve Part 3 B1 Listening | Tricks, Hacks & Audio","StudySmart",20,"Note how to track two speakers."),
  online(15,"Do Hören Teil 3 of the Modellsatz once, then check.")],
 [mc("How many items are in Hören Teil 3?","7","5","8","7 R/F-Items."),
  mc("How often do you hear the conversation?","once","twice","three times","einmal."),
  mc("Task type of Teil 3:","richtig/falsch","matching","a/b/c","Richtig oder Falsch."),
  mc("“Da hast du recht.” means:","You are right.","You have the right.","You have there.","Zustimmung."),
  mc("“Ich bin mir nicht sicher.” means:","I am not sure.","I am not safe.","I am not himself.","Unsicherheit."),
  mc("“Übrigens …” introduces …","an additional remark","a farewell","a question about the time","by the way."),
  mc("If a speaker changes his mind, you should …","follow the final statement","use the first statement","ignore both","Endgültige Meinung."),
  mc("How long is the reading time?","60 seconds","2 minutes","10 seconds","60 Sekunden."),
  mc("“Das kann ich mir nicht vorstellen.” expresses …","doubt","agreement","a request","Zweifel."),
  mc("It is important to …","note who says what","write full sentences","translate","Wer sagt was?"),
 ])

day("Hören Teil 4: a discussion – who says what?",
 "Follow a radio discussion and match eight statements to the presenter or one of two guests.",
 [N("Task","**8 items.** A moderator discusses with two guests (e.g. “Sollen kleine Kinder in die Kinderkrippe gehen?”). For each statement decide: **Moderator, Guest 1, Guest 2**. You hear the discussion **twice**."),
  N("Strategy","1. Note the three names and their **roles/positions** in the introduction.\n2. Listen for **opinion signals**: “Ich finde …”, “Meiner Meinung nach …”.\n3. On the second listening, check every item once more."),
  N("Discussion language","**Das sehe ich anders.** · **Da stimme ich Ihnen zu.** · **Einerseits … andererseits …** · **Dafür spricht, dass …** · **Ein wichtiger Punkt ist …** · **Ich möchte noch ergänzen …**")],
 [yt("cHcq6AtcZjM","Goethe Certificate B1 Model Set for Adults | Listening Part 4","E Language Studio Jaipur",17,"Listen to the example; note how opinions are signalled."),
  online(20,"Do Hören Teil 4 of the Modellsatz twice, then check.")],
 [mc("How many items are in Teil 4?","8","7","5","8 Zuordnungen."),
  mc("How often do you hear the discussion?","twice","once","three times","zweimal."),
  mc("Which people speak?","a moderator and two guests","two moderators","a teacher and students","Moderator + 2 Gäste."),
  mc("“Das sehe ich anders.” means:","I see it differently.","I see it another time.","I see him.","Widerspruch."),
  mc("“Da stimme ich Ihnen zu.” means:","I agree with you.","I vote for you.","I tune you.","Zustimmung."),
  mc("“Einerseits … andererseits …” means:","on the one hand … on the other hand …","in one part … in another part …","one side … no side","Abwägen."),
  mc("“Dafür spricht, dass …” means:","One argument in favour is that …","It is spoken for that …","That speaks for itself.","Argument dafür."),
  mc("“Ich möchte noch ergänzen …” means:","I want to add …","I want to complete …","I want to complement …","Ergänzung."),
  mc("At the start, you should note …","the names and roles","the time","the title only","Sprecher zuordnen."),
  mc("Task type of Teil 4:","matching (who says what)","true/false","multiple choice","Zuordnung."),
 ])

day("Hören: full module practice (40 minutes)",
 "Take a full Hören module under exam conditions and score it.",
 [N("How to do it","Use a quiet room, no pause. Read the tasks in the reading time, listen (1× or 2× as in the real exam), and after all four parts transfer your answers to the answer sheet (**5 minutes** are given for that).\nScore: **60% = 18 of 30**."),
  N("After the test","1. Count your points per part.\n2. Re-listen to every wrong item **with the transcript**.\n3. Write down the phrase or word you missed – that becomes tomorrow’s review list."),
  N("Listening habits (every day)","Slow German, DW Top-Thema, Easy German – 10 minutes a day, no subtitles first, then with.")],
 [online(45,"Full Hören module with audio (Modellsatz or Übungssatz). Score it: 18 of 30 to pass."),
  M("audio","Slow German – podcast for learners","Slow German (Annik Rubens)","https://slowgerman.com/",15,"Listen to one episode and write three new words you heard.")],
 [mc("How many minutes does the full Hören module take?","40","65","60","Hören 40 Minuten."),
  mc("How many points do you need out of 30 items?","18","20","15","60%."),
  mc("How much time is given to transfer answers to the answer sheet?","5 minutes","1 minute","10 minutes","Fünf Minuten."),
  mc("Which parts are heard once?","Teil 2 and Teil 3","Teil 1 and Teil 4","all parts","Teil 2 und 3 einmal."),
  mc("Which parts are heard twice?","Teil 1 and Teil 4","Teil 2 and Teil 3","none","Teil 1 und 4 zweimal."),
  mc("What do you do with wrong answers?","Re-listen with the transcript","Ignore them","Memorise the key","Analysieren."),
  mc("Total items of Hören:","30","20","40","10+5+7+8."),
  mc("A listening habit that helps:","10 minutes daily","only on exam day","only reading","täglich."),
  mc("A good rule when unsure:","give an answer anyway","leave blank","write a comment","Immer antworten."),
  mc("Which part is a discussion?","Teil 4","Teil 1","Teil 2","Radiosendung."),
 ])

# Schreiben
day("Schreiben Aufgabe 1: a personal e-mail",
 "Write a personal e-mail of about 80 words covering three points: describe, give reasons, and suggest a meeting.",
 [N("Task","**20 minutes**, about **80 words**. You write to a friend (e.g. who missed your birthday party): **1. Beschreiben** (how was it?), **2. Begründen** (what present do you like and why?), **3. Vorschlag** (suggest a meeting). You must cover **all three points**."),
  N("Structure and phrases","**Anrede:** Liebe Anna, / Lieber Tom,\n**Einleitung:** Wie geht es dir? Ich hoffe, du bist wieder gesund.\n**Hauptteil:** Die Feier war super, weil … · Das schönste Geschenk war …, denn …\n**Vorschlag:** Wie wäre es, wenn wir uns am Samstag treffen? · Hast du Lust, mit mir …?\n**Schluss:** Ich freue mich auf dich! Viele Grüße, Joy"),
  N("Scoring","Four criteria: **Erfüllung** (all points), **Kohärenz** (structure, connectors), **Wortschatz**, **Strukturen**. If you miss the task (0 points for Erfüllung), the whole task gets 0.")],
 [yt("GUiFLne10BE","SCHREIBEN B1: eine E-Mail schreiben","Karina Multilingual",12,"Note the structure and connectors; then write your own version."),
  modell(25,"Do Schreiben Aufgabe 1 (20 minutes), then compare with the sample answers at the back of the Modellsatz.")],
 [mc("About how many words for Aufgabe 1?","80","40","150","circa 80 Wörter."),
  mc("How long do you have for Aufgabe 1?","20 minutes","25 minutes","15 minutes","20 Minuten."),
  mc("How many points must you cover?","all three","two of three","only the first","alle drei Leitpunkte."),
  mc("A good greeting to a friend:","Liebe Anna,","Sehr geehrte Frau Anna,","Hallo Damen und Herren,","informell."),
  mc("A good ending for a friend:","Viele Grüße","Mit freundlichen Grüßen","Hochachtungsvoll","informell."),
  mc("“Wie wäre es, wenn wir uns am Samstag treffen?” is …","a suggestion","a complaint","an excuse","Vorschlag."),
  mc("What is the main criterion?","Erfüllung (covering all points)","only spelling","only length","Erfüllung."),
  fill("Ich hoffe, du bist wieder ___. (gesund)",["gesund"],"Ich hoffe, du bist gesund."),
  fill("Die Feier war super, ___ alle Freunde da waren. (because)",["weil"],"weil + Nebensatz."),
  fill("Hast du Lust, mit mir ins Kino ___ gehen? (zu)",["zu"],"Lust haben, … zu + Infinitiv."),
 ])

day("Schreiben Aufgabe 2: an opinion post",
 "Write a discussion/forum post of about 80 words giving your opinion with reasons and an example.",
 [N("Task","**25 minutes**, about **80 words**. You read a forum comment (e.g. “Persönliche Kontakte und Internet”) and write **your own opinion**."),
  N("Structure","1. **Reaction:** Ich stimme … (nicht) zu. / Wie Tanja finde ich …\n2. **Opinion + reason:** Meiner Meinung nach …, weil …\n3. **Example:** Zum Beispiel …\n4. **Counter-argument or balance:** Einerseits …, andererseits …\n5. **Conclusion:** Deshalb denke ich, dass …"),
  N("Connectors","**weil, denn, deshalb, außerdem, trotzdem, obwohl, zum Beispiel, einerseits … andererseits, zwar … aber, deshalb, daher**")],
 [yt("O_Q9MpxjsrI","Goethe Prüfung B1: Kommentar / Forumsbeitrag schreiben","Lingster Academy",9,"Note the structure and connectors; write one post yourself."),
  modell(30,"Do Schreiben Aufgabe 2 (25 minutes) and compare with the sample answers.")],
 [mc("About how many words for Aufgabe 2?","80","40","120","circa 80."),
  mc("How long do you have?","25 minutes","15 minutes","10 minutes","25 Minuten."),
  mc("What is expected?","your own opinion with reasons","a summary of the comment","a letter to the editor","persönliche Meinung."),
  mc("A good opener for your opinion:","Meiner Meinung nach …","Sehr geehrte Damen und Herren","Liebe Anna","Meinungsäußerung."),
  mc("“Zum Beispiel …” introduces …","an example","a conclusion","a greeting","Beispiel."),
  fill("___ finde ich, dass persönliche Treffen wichtig sind. (In my opinion → Meiner Meinung ___)",["nach","Meiner Meinung nach"],"Meiner Meinung nach."),
  fill("Das Internet ist praktisch, ___ es kann persönliche Treffen nicht ersetzen. (but)",["aber"],"aber."),
  fill("___ ... andererseits (on the one hand)",["Einerseits"],"einerseits … andererseits."),
  mc("Which connector shows contrast?","trotzdem","deshalb","außerdem","Gegensatz."),
  mc("What do you do at the end?","Conclude briefly","Add a new topic","Write a greeting","Schluss."),
 ])

day("Schreiben Aufgabe 3: a formal e-mail",
 "Write a polite formal e-mail of about 40 words: apologise or ask for something and give a reason.",
 [N("Task","**15 minutes**, about **40 words**. You write to a teacher, landlord or company (e.g. to Frau Müller: you cannot come to a meeting). Use **Sie**, a formal greeting and a formal closing."),
  N("Structure and phrases","**Anrede:** Sehr geehrte Frau Müller, / Sehr geehrter Herr Schmidt, / Sehr geehrte Damen und Herren,\n**Bitte/Entschuldigung:** leider kann ich … nicht kommen, weil … · Ich bitte Sie um Verständnis. · Könnten Sie mir bitte …?\n**Vorschlag:** Könnten wir einen neuen Termin vereinbaren?\n**Schluss:** Vielen Dank für Ihr Verständnis. Mit freundlichen Grüßen, Joy Infant"),
  N("Tip","Do not forget **Anrede** and **Gruß** – the exam asks for them. Count ~40 words; stay short.")],
 [yt("kxchc-JAwR8","B1 Goethe | Writing 3) formal email | asking for information | internship","Deutsch mit Christiane",11,"Note the formal phrases; write your own e-mail."),
  modell(20,"Do Schreiben Aufgabe 3 (15 minutes), compare with the sample answer.")],
 [mc("About how many words for Aufgabe 3?","40","80","120","circa 40."),
  mc("How long do you have?","15 minutes","20 minutes","25 minutes","15 Minuten."),
  mc("A formal greeting:","Sehr geehrte Frau Müller,","Liebe Frau Müller,","Hallo Frau Müller,","formell."),
  mc("A formal closing:","Mit freundlichen Grüßen","Bis bald","Tschüss","formell."),
  mc("Which phrase apologises politely?","Ich bitte um Verständnis.","Das ist mir egal.","Ich komme nicht.","höflich."),
  fill("Leider ___ ich am Dienstag nicht kommen. (können)",["kann"],"ich kann."),
  fill("Könnten Sie mir bitte einen neuen ___ nennen? (Termin)",["Termin"],"einen Termin nennen."),
  fill("Ich bitte Sie um ___. (Verständnis)",["Verständnis","Verstaendnis"],"um Verständnis bitten."),
  mc("Which is too informal for this task?","Hi Frau Müller, ich komm nicht, sorry!","Sehr geehrte Frau Müller","Vielen Dank für Ihr Verständnis","Register."),
  mc("Which must be included?","Anrede and Gruß","a PS","your address","Anrede + Gruß."),
 ])

day("Schreiben: full module practice (60 minutes)",
 "Write all three tasks in one hour and self-check with the scoring criteria.",
 [N("Time plan","**Aufgabe 1: 20 min · Aufgabe 2: 25 min · Aufgabe 3: 15 min.** Write **legibly** in pen; no dictionary or phone."),
  N("Self-check list","☐ All points covered? ☐ Greeting and closing? ☐ Words near 80 / 80 / 40? ☐ Connectors (weil, deshalb, obwohl, außerdem)? ☐ Verb in 2nd position and at end of subordinate clauses? ☐ Capital letters on nouns? ☐ Sie vs du correct?"),
  N("Scoring criteria","**Erfüllung, Kohärenz, Wortschatz, Strukturen** for each task; 60% needed to pass. If you can, let a teacher or a language partner correct your text.")],
 [uebung(65,"Do the Schreiben module of the Übungssatz under time pressure and use the self-check list."),
  yt("iTDnapgGo9A","GERMAN B1 Exam WRITING GUIDE – Deutsch Goethe B1 Schreiben","Learn German Relaxed",5,"Check your texts against this quick guide.")],
 [mc("Total time for Schreiben:","60 minutes","40 minutes","90 minutes","60 Minuten."),
  mc("Time for Aufgabe 2:","25 minutes","20 minutes","15 minutes","25 Minuten."),
  mc("Which criterion is NOT one of the four?","Handwriting beauty","Erfüllung","Kohärenz","Erfüllung, Kohärenz, Wortschatz, Strukturen."),
  mc("What must you write in Aufgabe 3?","Anrede and Gruß","only the reason","a poem","Formell."),
  mc("Is a dictionary allowed?","No","Yes","Only online","Keine Hilfsmittel."),
  mc("You should write in …","pen (not pencil)","pencil","any","kein Bleistift."),
  fill("Ich schreibe ___ meinen Freund. (to, an + Akk.)",["an"],"schreiben an + Akk."),
  fill("Ich habe mich sehr ___ deine E-Mail gefreut. (über)",["über","ueber"],"sich freuen über."),
  fill("Ich würde mich freuen, ___ du kommst. (wenn)",["wenn"],"Ich würde mich freuen, wenn …"),
  mc("What is the best use of the last minutes?","Check greeting, closing and verb positions","Start a new text","Count letters","Kontrolle."),
 ])

# Sprechen
day("Sprechen Teil 1: planning something together",
 "Plan an event with a partner: make suggestions, react, and agree (about 3 minutes).",
 [N("Task","You and your partner get a situation with four bullet points (e.g. visit a course friend in hospital: when? how to get there? what to bring? how to help?). **Both** must make suggestions, react to the other, and agree on a plan."),
  N("Redemittel","**Vorschlag:** Wie wäre es, wenn wir …? · Ich schlage vor, dass wir … · Wollen wir …? · Was hältst du davon, wenn …?\n**Zustimmung:** Das ist eine gute Idee. · Einverstanden! · Genau, so machen wir es.\n**Ablehnung mit Alternative:** Das finde ich schwierig, denn … Wie wäre es stattdessen mit …?\n**Abschluss:** Dann machen wir es so."),
  N("Tips","Cover all four bullet points. Ask your partner questions (Was meinst du?). Silence and reading aloud from notes cost points.")],
 [yt("I7JwVznZrlI","B1 Prüfung: Gemeinsam etwas planen – Tipps & Redemittel für die Prüfung","Deutsch mit Tina",7,"Watch the model dialogue and note the phrases."),
  modell(20,"Read the Sprechen Teil 1 tasks in the Modellsatz; practise one aloud with a partner or by recording yourself.")],
 [mc("How long is Sprechen Teil 1?","about 3 minutes","about 10 minutes","about 30 seconds","circa drei Minuten."),
  mc("What must you do in Teil 1?","plan together and reach a decision","give a monologue","answer questions","Gemeinsam planen."),
  mc("A suggestion:","Wie wäre es, wenn wir am Freitag gehen?","Ich weiß nicht.","Das ist mir egal.","Vorschlag."),
  mc("Which phrase agrees?","Einverstanden!","Auf keinen Fall.","Vielleicht nie.","Zustimmung."),
  mc("Which phrase rejects politely?","Das finde ich schwierig, denn …","Nein.","Quatsch.","höflich ablehnen."),
  fill("Wie ___ es, wenn wir Blumen mitbringen? (wäre)",["wäre","waere"],"Wie wäre es, wenn …"),
  fill("Was ___ du davon, wenn wir ihn abholen? (halten)",["hältst","haeltst"],"Was hältst du davon?"),
  fill("Ich ___ vor, dass wir zusammen fahren. (vorschlagen)",["schlage"],"Ich schlage vor, dass …"),
  mc("Should you cover all four bullet points?","Yes","No","Only two","Alle Punkte."),
  mc("Should you ask your partner questions?","Yes, it shows interaction","No","Only at the end","Interaktion."),
 ])

day("Sprechen Teil 2: a presentation",
 "Give a structured monologue of about 3 minutes on a topic with five prompts.",
 [N("Task","You choose **one of two topics** and present with **5 slides/prompts** (~3 minutes): 1. Introduction (topic + why you chose it), 2. Your own experience, 3. Situation in your country, 4. Pros and cons, 5. Conclusion + thanks. Preparation: 15 minutes together for all parts."),
  N("Structure and phrases","**Einleitung:** Ich möchte über das Thema … sprechen. · Ich habe dieses Thema gewählt, weil …\n**Erfahrung:** Ich habe schon mal … · Bei mir war das so: …\n**Land:** In meinem Heimatland ist es üblich, dass …\n**Vor-/Nachteile:** Ein Vorteil ist … Ein Nachteil ist … · Einerseits …, andererseits …\n**Schluss:** Zum Schluss möchte ich sagen … · Vielen Dank für Ihre Aufmerksamkeit."),
  N("Tips","Do not memorise a text. Speak in **short sentences** and use connectors. Look at the audience, not at your paper. Stay ~3 minutes.")],
 [yt("jVGnSYo_aMQ","B1 - Lesson 30 | eine Präsentation halten | Goethe Zertifikat Teil 2 Sprechen","Learn German",10,"Note the structure and the phrases; record your own 3-minute talk."),
  modell(20,"Choose a topic from the Modellsatz Sprechen Teil 2, prepare in 15 minutes, and present to a phone recording.")],
 [mc("How long is the presentation?","about 3 minutes","about 10 minutes","about 30 seconds","circa drei Minuten."),
  mc("How many prompts/slides are there?","5","3","8","fünf Folien."),
  mc("A good introduction:","Ich möchte über das Thema … sprechen.","Also …","Ich habe keine Ahnung.","Einleitung."),
  mc("A phrase for pros and cons:","Ein Vorteil ist … / Ein Nachteil ist …","Ich mag es nicht.","Vielleicht.","Vor- und Nachteile."),
  mc("A good conclusion:","Vielen Dank für Ihre Aufmerksamkeit.","Tschüss!","Das war es.","Schluss."),
  fill("Ich habe dieses Thema gewählt, ___ es mich interessiert. (weil)",["weil"],"weil."),
  fill("In meinem Heimatland ist es üblich, ___ man früh heiratet. (dass)",["dass"],"üblich, dass …"),
  mc("Should you read from a script?","No, speak freely with keywords","Yes, word by word","Only the first slide","Frei sprechen."),
  mc("How many topics can you choose from?","two","three","one","Thema 1 oder 2."),
  mc("What helps most?","short sentences and connectors","long complex sentences","memorised poem","Klarheit."),
 ])

day("Sprechen Teil 3: feedback and questions",
 "Respond to feedback on your presentation and give feedback plus one question to your partner.",
 [N("Task","**About 2 minutes.** After your partner’s presentation you (a) give **feedback** (what you liked, what was new) and (b) ask **one question**. After your own presentation you answer their feedback and question."),
  N("Redemittel","**Feedback:** Deine Präsentation hat mir gut gefallen, weil … · Besonders interessant fand ich … · Neu für mich war, dass …\n**Frage:** Wie ist das in deinem Land? · Was denkst du über …? · Hast du schon mal …?\n**Antwort:** Das ist eine gute Frage. Ich glaube, … · Danke für die Rückmeldung!"),
  N("Tips","Stay friendly and concrete. Do not only say “gut”; add a **reason**. Answer in full sentences.")],
 [yt("Su4LC93w86I","Deutsch B1-Prüfung: Feedback auf einen kurzen Vortrag geben & auf Feedback reagieren","Schneereima",4,"Note phrases for giving and receiving feedback."),
  modell(15,"Read Sprechen Teil 3 in the Modellsatz; practise feedback + question aloud.")],
 [mc("How long is Teil 3?","about 2 minutes","about 10 minutes","5 minutes","circa 2 Minuten."),
  mc("What must you do after your partner’s talk?","give feedback and ask a question","give a speech","end the exam","Rückmeldung + Frage."),
  mc("A good feedback sentence:","Besonders interessant fand ich …","Es war okay.","Keine Ahnung.","konkret."),
  mc("A good question:","Wie ist das in deinem Land?","Wie spät ist es?","Bist du fertig?","zum Thema."),
  mc("Your answer to feedback:","Danke für die Rückmeldung!","Hm.","Nein.","höflich."),
  fill("Deine Präsentation hat mir gut ___. (gefallen)",["gefallen"],"gefallen."),
  fill("Neu für mich war, ___ es dort so viele Radwege gibt. (dass)",["dass"],"dass-Satz."),
  fill("Was ___ du über dieses Thema? (denken)",["denkst"],"denken über + Akk."),
  mc("Adding a reason is …","important","forbidden","only for C1","weil …"),
  mc("Short answers like “ja/nein” only are …","not enough","enough","required","ganze Sätze."),
 ])

day("Sprechen: full mock exam (record yourself)",
 "Do the whole Sprechen module with a partner or alone and listen back.",
 [N("How to do it","**15 minutes preparation, 15 minutes exam** (two candidates). If you have no partner, play both roles by recording: Teil 1 as a dialogue, Teil 2 as a solo talk, Teil 3 as feedback to your recording."),
  N("Self-check","Did I cover all bullet points? Did I use connectors? Was my pronunciation clear? Did I ask a real question? Did I stay within ~3 minutes per part?"),
  N("Assessment","Sprechen is assessed on **task fulfilment, interaction, vocabulary, structures and pronunciation**. Aim for clear, connected speech rather than perfection.")],
 [yt("YggtVH9BoSE","Goethe-Zertifikat B1 – Deutschprüfung Modul Sprechen | German B1 Oral Exam","24h Deutsch",13,"Watch a sample oral exam, then do yours."),
  uebung(30,"Do all three Sprechen parts from the Übungssatz and record.")],
 [mc("Total time for Sprechen (two candidates):","15 minutes","40 minutes","5 minutes","15 Min."),
  mc("Preparation time:","15 minutes","5 minutes","1 minute","15 Minuten."),
  mc("Which part is a monologue?","Teil 2","Teil 1","Teil 3","Präsentation."),
  mc("Which part is planning?","Teil 1","Teil 2","Teil 3","Gemeinsam planen."),
  mc("Which part needs a question to your partner?","Teil 3","Teil 1","Teil 2","Feedback + Frage."),
  mc("If you do not know a word, you should …","paraphrase","stay silent","switch language","Umschreiben."),
  fill("Ich meine, ___ wir am Samstag fahren sollten. (dass)",["dass"],"dass-Satz."),
  fill("Ich würde vorschlagen, ___ wir uns um 10 Uhr treffen. (dass)",["dass"],"dass."),
  mc("Which is best?","Speak in short clear sentences","Speak fast","Speak only English words","Klarheit."),
  mc("What do you do after the mock?","Listen back and note mistakes","Delete it","Post it","Auswerten."),
 ])

# Review
day("Grammar review I: verbs and tenses",
 "Review the verb forms tested at B1: tenses, passive, Konjunktiv II, modals, separable and reflexive verbs.",
 [N("Tenses","**Perfekt** (spoken): Ich habe gegessen. Ich bin gegangen. **Präteritum** (written/story): ging, kam, war, hatte, sagte. **Plusquamperfekt:** hatte/war + Partizip II. **Futur I:** werden + Infinitiv."),
  N("Passive and Konjunktiv II","**Passiv:** wird gebaut / wurde gebaut / ist gebaut worden / kann gebaut werden. **Konjunktiv II:** wäre, hätte, würde + Infinitiv, könnte, sollte. Wishes, advice, polite requests, unreal conditions (wenn ich Zeit hätte, …)."),
  N("Verbs","**Modal verbs:** können, müssen, dürfen, wollen, sollen, mögen. **Reflexive:** sich freuen auf/über, sich interessieren für, sich ärgern über. **Separable:** aufstehen – ich stehe auf – aufgestanden – aufzustehen. **lassen + Infinitiv:** Ich lasse mein Auto reparieren.")],
 [uebung(20,"Do the Lesen and Schreiben tasks of the Übungssatz that test verbs and underline every verb form you meet."),
  yt("JgvyIFFS4Ps","PASSIV: alle Zeitformen + Geheimnis","Karina Multilingual",12,"Review the passive in all tenses.")],
 [fill("Gestern ___ ich lange im Büro. (sein, Präteritum)",["war"],"war."),
  fill("Er ist nach Berlin ___. (fahren, Partizip II)",["gefahren"],"gefahren."),
  fill("Nachdem sie gegessen ___, gingen sie spazieren. (haben, Plusquamperfekt)",["hatten"],"hatten gegessen."),
  fill("Das Haus ___ 1950 gebaut. (werden, Präteritum Passiv)",["wurde"],"wurde gebaut."),
  fill("Das Haus ist 1950 gebaut ___. (Perfekt Passiv)",["worden"],"worden."),
  fill("Wenn ich reich ___, würde ich reisen. (sein, Konjunktiv II)",["wäre","waere"],"wäre."),
  fill("Du ___ mehr schlafen. (sollen, Konjunktiv II)",["solltest"],"du solltest."),
  fill("Ich ___ gern einen Kaffee. (haben, Konjunktiv II – polite)",["hätte","haette"],"Ich hätte gern …"),
  fill("Ich freue mich ___ das Wochenende. (auf)",["auf"],"sich freuen auf + Akk."),
  fill("Ich ärgere mich ___ den Lärm. (über)",["über","ueber"],"sich ärgern über."),
  fill("Er hat vergessen, mich anzu___. (rufen)",["rufen"],"anzurufen."),
  fill("Ich lasse mein Fahrrad ___. (reparieren)",["reparieren"],"lassen + Infinitiv."),
  mc("Which sentence is correct?","Er hat gestern lange geschlafen.","Er ist gestern lange geschlafen.","Er hat gestern lange schlafen.","schlafen + haben."),
  mc("Which is the correct Plusquamperfekt?","Ich hatte das Buch gelesen.","Ich habe das Buch gelesen gehabt.","Ich bin das Buch gelesen.","hatte + Partizip II."),
 ])

day("Grammar review II: sentences, cases and nouns",
 "Review connectors, subordinate clauses, relative clauses, cases and noun formation.",
 [N("Connectors","**Position 0:** und, oder, aber, denn, sondern. **Adverbs (verb 2nd):** deshalb, trotzdem, deswegen, dagegen, jedoch. **Subordinate (verb at end):** weil, dass, ob, obwohl, wenn, als, damit, bevor, nachdem, während, seit. **Double:** entweder … oder, weder … noch, sowohl … als auch, nicht nur … sondern auch."),
  N("Relative clauses and cases","**Relativpronomen:** der/die/das, den (Akk. mask.), dem, denen; **dessen/deren** (Genitiv); **wo** for places. **Genitiv prepositions:** wegen, trotz, während, statt. **n-Deklination:** der Student, den/dem/des Studenten. **Adjective endings:** ein großer Tisch, eine große Stadt, ein großes Haus."),
  N("Nouns","**-heit/-keit/-ung** → die · **-chen/-lein** → das · Nominalisation: das Lernen, die Arbeit. **wo-compounds:** worauf, womit, wofür, worüber. **Comparison:** so … wie / -er als / am -sten.")],
 [uebung(20,"Do the Lesen part of the Übungssatz and mark every connector and relative clause."),
  yt("K0SGXxkB5ZM","DER GENITIV - Einfach erklärt für Deutschlerner A2-C1","Lingster Academy",13,"Review the genitive endings and prepositions.")],
 [fill("Ich bleibe zu Hause, ___ ich krank bin. (weil)",["weil"],"weil."),
  fill("Es regnet, ___ gehen wir spazieren. (trotzdem)",["trotzdem"],"trotzdem."),
  fill("Ich weiß nicht, ___ er kommt. (ob)",["ob"],"ob."),
  fill("Ich lerne, ___ ich die Prüfung bestehe. (damit)",["damit"],"damit."),
  fill("Er ist nicht dumm, ___ faul. (sondern)",["sondern"],"sondern."),
  fill("Das ist der Mann, ___ ich gestern gesehen habe. (den)",["den"],"den."),
  fill("Das ist die Frau, ___ Tochter Ärztin ist. (deren)",["deren"],"deren."),
  fill("___ des Regens gehen wir spazieren. (trotz)",["Trotz"],"trotz + Genitiv."),
  fill("Ich helfe dem Kollege___. (n-Deklination)",["n","Kollegen"],"dem Kollegen."),
  fill("Ich habe ein neu___ Auto. (Nominativ neutrum, mit ein)",["es"],"ein neues Auto."),
  fill("Er hat weder Zeit ___ Geld. (noch)",["noch"],"weder … noch."),
  mc("Which noun is correct?","die Möglichkeit","der Möglichkeit","das Möglichkeit","-keit = die."),
  mc("Which is correct?","Er ist größer als ich.","Er ist größer wie ich.","Er ist so größer als ich.","als nach Komparativ."),
  mc("Which sentence is correct?","Ich glaube, dass er heute kommt.","Ich glaube, dass er kommt heute.","Ich glaube, dass kommt er heute.","Verb am Ende."),
 ])

day("Vocabulary and Redemittel review",
 "Review the big topics of the exam and the phrases you will use in writing and speaking.",
 [N("Topics","Arbeit und Beruf · Wohnen · Gesundheit · Reisen · Freizeit und Hobbys · Schule und Ausbildung · Umwelt · Medien und Internet · Freundschaft und Familie · Feste und Feiertage · Einkaufen · Gesellschaft (Wahlen, Migration)."),
  N("Redemittel – opinion and reasoning","**Meiner Meinung nach …** · **Ich finde, dass …** · **Ich bin der Ansicht, dass …** · **Ich stimme zu / nicht zu** · **Einerseits … andererseits …** · **Ein Vorteil/Nachteil ist …** · **Ich habe die Erfahrung gemacht, dass …**"),
  N("Redemittel – speaking help","**Was meinst du?** · **Könnten Sie das bitte wiederholen?** · **Ich meine …** · **Das hängt davon ab …** · **Mit anderen Worten …** · **Wie sagt man …?**")],
 [yt("m9N-q74a5iE","MEINUNG ÄUßERN / REDEMITTEL (mündliche und schriftliche Prüfung)","Dein Sprachcoach",11,"Collect ten opinion phrases into your notebook."),
  yt("Mhs00ZotMZc","B-Level-Wortschatz | B1 / B2 | Learn German","Benjamin - Der Deutschlehrer",8,"Note new words for your topics.")],
 [mc("“Meiner Meinung nach …” is used to …","give your opinion","ask a question","greet","Meinungsäußerung."),
  mc("“Ich habe die Erfahrung gemacht, dass …” means:","I have experienced that …","I made an experiment that …","I did research that …","Erfahrung."),
  mc("“Das hängt davon ab, …” means:","That depends on …","That hangs from …","That depends less","kommt darauf an."),
  mc("“Mit anderen Worten …” means:","in other words","with other words in mind","with different worlds","Umschreibung."),
  mc("“Könnten Sie das bitte wiederholen?” is …","a polite request to repeat","a complaint","an apology","höflich."),
  mc("“Vorteil” is the opposite of …","Nachteil","Nachbar","Nachweis","Vorteil – Nachteil."),
  mc("“die Gesellschaft” means:","society","company (business)","fellowship of a club","Gesellschaft."),
  mc("“die Umwelt” means:","environment","surroundings only","world map","Umwelt."),
  mc("“die Ausbildung” means:","apprenticeship, training","education in general","exercise","Ausbildung."),
  mc("“sich bewerben um” means:","to apply for","to review","to praise","Bewerbung."),
  fill("Ich bin der ___, dass Sport wichtig ist. (Ansicht)",["Ansicht"],"der Ansicht sein."),
  fill("Wie ___ man das auf Deutsch? (sagt)",["sagt"],"Wie sagt man …?"),
 ])

day("Full mock I: Lesen and Hören",
 "Take a complete Lesen and Hören together (105 minutes) and analyse mistakes.",
 [N("Plan","Lesen 65 min → 10 min break → Hören 40 min. Use pen, no dictionary, timer running."),
  N("Analysis","For each wrong item: (1) which part, (2) why (vocabulary, trap, time), (3) write the correct answer with the sentence from the text or transcript."),
  N("Targets","Lesen ≥ 18/30 and Hören ≥ 18/30 = pass. Aim for 22+ for a safe margin.")],
 [uebung(65,"Full Lesen module of the Übungssatz, timed."),
  online(45,"Full Hören module with audio, exam conditions.")],
 [mc("How long is Lesen?","65 minutes","40 minutes","60 minutes","Lesen 65."),
  mc("How long is Hören?","40 minutes","65 minutes","60 minutes","Hören 40."),
  mc("How many points to pass a module?","60%","70%","50%","60 %."),
  mc("How many items in Lesen?","30","20","40","30."),
  mc("How many items in Hören?","30","20","40","30."),
  mc("Wrong answer analysis should include …","cause and correct answer","just the score","nothing","Analyse."),
  mc("How many correct items give 60% of 30?","18","15","20","18."),
  mc("A safe target is …","22 or more","18 exactly","10","Sicherheitsabstand."),
  mc("A dictionary is …","not allowed","allowed","only for Lesen","Keine Hilfsmittel."),
  mc("Answers are written …","in pen","in pencil","on the question sheet only","kein Bleistift."),
 ])

day("Full mock II: Schreiben and Sprechen",
 "Take a complete Schreiben (60 min) and Sprechen (15 min + 15 min preparation) mock and analyse them.",
 [N("Plan","Schreiben 60 min → break → Sprechen (record). Correct writing with the four criteria; ask a teacher or partner for feedback if possible."),
  N("Checklist","Writing: all points covered, greeting/closing, connectors, ~80/80/40 words. Speaking: 4 bullet points, 5 slides, feedback + question, pronunciation."),
  N("Reminder","This course follows the **Goethe-Zertifikat B1**. If you sit **telc B1** or **DTZ**, use their official model tests for the same skills too.")],
 [uebung(60,"Full Schreiben module of the Übungssatz, timed."),
  yt("JhyQ0hj1ck0","Die B1 Mündliche Prüfung bestehen: Goethe und telc","Lingster Academy",13,"Compare Goethe and telc oral exam formats.")],
 [mc("How long is Schreiben?","60 minutes","40 minutes","75 minutes","60."),
  mc("How long is Sprechen (two candidates)?","15 minutes","60 minutes","5 minutes","15."),
  mc("How many Schreiben tasks?","3","2","5","3."),
  mc("How many Sprechen parts?","3","2","4","3."),
  mc("Aufgabe 1 length:","about 80 words","about 40 words","about 200 words","80."),
  mc("Aufgabe 3 length:","about 40 words","about 80 words","about 120 words","40."),
  mc("Which exam formats differ slightly?","telc and DTZ vs Goethe","none","only Lesen","Prüfungsform prüfen."),
  fill("Ich schreibe Ihnen ___ meines Termins. (because of)",["wegen","Wegen"],"wegen + Genitiv."),
  fill("Ich würde ___ freuen, wenn du kommst. (mich)",["mich"],"sich freuen."),
  mc("What do you do after the mock?","Correct and note repeated mistakes","Nothing","Repeat immediately","Fehleranalyse."),
 ])

# Final mock (30 questions)
final_q = [
 mc("How many points do you need to pass a module?","60 of 100","70 of 100","50 of 100","60 %."),
 mc("How long is the Hören module?","40 minutes","65 minutes","60 minutes","40."),
 mc("Lesen Teil 3: what do you write if no ad matches?","0","X","–","0."),
 mc("Hören Teil 4 has …","8 items","5 items","10 items","8."),
 mc("Schreiben Aufgabe 1 has about …","80 words","40 words","120 words","80."),
 mc("Sprechen Teil 2 is …","a presentation","a planning dialogue","a written text","Präsentation."),
 fill("Ich weiß nicht, ___ er heute kommt.",["ob"],"ob."),
 fill("Es regnet. ___ gehe ich spazieren.",["Trotzdem"],"trotzdem."),
 fill("Er kommt nicht, ___ er krank ist. (because)",["weil"],"weil."),
 fill("Er ist nicht müde, ___ hungrig.",["sondern"],"sondern."),
 fill("Ich lerne, ___ ich die Prüfung bestehe.",["damit"],"damit."),
 fill("Ich habe keine Lust, heute ___ arbeiten.",["zu"],"zu + Infinitiv."),
 fill("___ ich ins Bett gehe, putze ich die Zähne.",["Bevor"],"bevor."),
 fill("Nachdem er gegessen ___, ging er.",["hatte"],"Plusquamperfekt."),
 fill("Der Landtag ___ gewählt.",["wird"],"Passiv."),
 fill("Wenn ich Zeit ___, würde ich reisen.",["hätte","haette"],"Konjunktiv II."),
 fill("Du ___ mehr schlafen. (sollen, Konjunktiv II)",["solltest"],"solltest."),
 fill("___ des Wetters bleiben wir zu Hause. (wegen)",["Wegen"],"wegen."),
 fill("Der Mann, ___ Tochter Ärztin ist, wohnt hier.",["dessen"],"dessen."),
 fill("Die Stadt, ___ ich wohne, ist klein.",["wo","in der"],"wo."),
 fill("Ich kenne den Student___.",["en","Studenten"],"n-Deklination."),
 fill("Er lässt sich die Haare ___. (schneiden)",["schneiden"],"lassen."),
 fill("___ interessierst du dich? (wofür)",["Wofür","Wofuer"],"wo-Kompositum."),
 fill("Sehr geehrte Frau Müller, ... Mit freundlichen ___ (Grüßen)",["Grüßen","Gruessen"],"Mit freundlichen Grüßen."),
 mc("Which suggestion is polite?","Wie wäre es, wenn wir uns am Samstag treffen?","Du musst Samstag kommen.","Samstag, basta!","Vorschlag."),
 mc("Which phrase gives your opinion?","Meiner Meinung nach ist das wichtig.","Es ist Samstag.","Guten Tag.","Meinung."),
 mc("“ausfallen” (course) means:","to be cancelled","to fall out","to stand out","ausfallen."),
 mc("“die Ermäßigung” means:","discount","moderation","reduction of pain","Ermäßigung."),
 mc("“bewerben um” means:","to apply for","to praise","to review","Bewerbung."),
 mc("“die Gesellschaft” means:","society","shop","assembly","Gesellschaft."),
]
day("Final mock exam and exam-day plan",
 "A last 30-question mock, a checklist for the day before the exam, and a plan for the exam morning.",
 [N("Checklist for the day before","☐ ID/passport ☐ Registration confirmation and exam room/time ☐ Pen(s), no pencil ☐ Route to the test centre ☐ Sleep – no cramming ☐ Light review of Redemittel (30 minutes)"),
  N("On the exam day","Arrive 30 minutes early. Answer every item (no penalty for guessing). In Lesen and Hören transfer answers on time. In Schreiben stay near the word counts and always write greeting/closing. In Sprechen speak in short clear sentences and ask real questions."),
  N("After this course","You have completed A1 → B1 study: 228 lessons, tests and exam training. Keep listening and speaking daily; book your exam and, if possible, sit a model test at your test centre.")],
 [modell(180,"Optional: a complete Modellsatz (all four modules) as a last rehearsal, only if you have time."),
  online(60,"Use the online practice tests with audio for a last listening run.")],
 final_q)

assert len(D)==25, len(D)
json.dump(D, open("content/src/exam-b1.json","w"), ensure_ascii=False, indent=0)
print("ok", len(D), sum(len(d["quiz"]) for d in D))
